import pg from 'pg'

const { Pool } = pg

let pool

function getPool() {
  const connectionString = process.env.POSTGRES_URL || process.env.DATABASE_URL
  if (!connectionString) {
    throw new Error('Falta configurar POSTGRES_URL en Vercel.')
  }

  if (!pool) {
    pool = new Pool({
      connectionString,
      ssl: connectionString.includes('localhost') ? false : { rejectUnauthorized: false }
    })
  }

  return pool
}

export async function query(text, values) {
  return getPool().query(text, values)
}

export async function ensureSchema() {
  await query(`
    CREATE TABLE IF NOT EXISTS transactions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      external_id TEXT NOT NULL UNIQUE,
      fecha DATE NOT NULL,
      descripcion TEXT NOT NULL,
      clasificacion TEXT,
      tipo TEXT,
      abono BIGINT NOT NULL DEFAULT 0,
      gasto BIGINT NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS idx_transactions_fecha ON transactions(fecha);
    CREATE INDEX IF NOT EXISTS idx_transactions_tipo ON transactions(tipo);
    CREATE INDEX IF NOT EXISTS idx_transactions_clasificacion ON transactions(clasificacion);
  `)
}

export async function listTransactions() {
  await ensureSchema()
  const result = await query(`
    SELECT fecha::text AS fecha, descripcion, clasificacion, tipo, abono, gasto
    FROM transactions
    ORDER BY fecha ASC, id ASC
  `)

  return result.rows.map((row) => ({
    ...row,
    abono: Number(row.abono),
    gasto: Number(row.gasto)
  }))
}

export async function upsertTransactions(rows) {
  await ensureSchema()

  for (const row of rows) {
    await query(
      `
        INSERT INTO transactions (
          external_id, fecha, descripcion, clasificacion, tipo, abono, gasto
        ) VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT (external_id) DO UPDATE SET
          fecha = EXCLUDED.fecha,
          descripcion = EXCLUDED.descripcion,
          clasificacion = EXCLUDED.clasificacion,
          tipo = EXCLUDED.tipo,
          abono = EXCLUDED.abono,
          gasto = EXCLUDED.gasto,
          updated_at = CURRENT_TIMESTAMP
      `,
      [
        row.externalId,
        row.fecha,
        row.descripcion,
        row.clasificacion,
        row.tipo,
        row.abono,
        row.gasto
      ]
    )
  }
}

export async function deleteMissingSheetTransactions(worksheetName, externalIds) {
  await ensureSchema()
  const prefix = `${worksheetName}:%`

  if (externalIds.length === 0) {
    return query('DELETE FROM transactions WHERE external_id LIKE $1', [prefix])
  }

  return query(
    `DELETE FROM transactions
     WHERE external_id LIKE $1
       AND NOT (external_id = ANY($2::text[]))`,
    [prefix, externalIds]
  )
}

export async function countTransactions() {
  await ensureSchema()
  const result = await query('SELECT COUNT(*)::int AS total FROM transactions')
  return result.rows[0].total
}